use std::path::Path;

use anyhow::Context;
use sqlx::postgres::PgPoolOptions;
use sqlx::{PgPool, Row, SqlitePool};

use crate::storage::connect_sqlite;

#[derive(Debug, Clone, Default)]
pub struct HelpdeskPostgresBootstrapSummary {
    pub authorized_agents: usize,
    pub agents: usize,
    pub tickets: usize,
    pub assignments: usize,
    pub heartbeats: usize,
    pub audit_events: usize,
}

impl HelpdeskPostgresBootstrapSummary {
    fn from_snapshot(snapshot: &HelpdeskSnapshot) -> Self {
        Self {
            authorized_agents: snapshot.authorized_agents.len(),
            agents: snapshot.agents.len(),
            tickets: snapshot.tickets.len(),
            assignments: snapshot.assignments.len(),
            heartbeats: snapshot.heartbeats.len(),
            audit_events: snapshot.audit_events.len(),
        }
    }
}

const POSTGRES_HELPDESK_SCHEMA: &[&str] = &[
    r#"
    CREATE TABLE IF NOT EXISTS helpdesk_authorized_agents (
        agent_id TEXT PRIMARY KEY,
        display_name TEXT,
        created_at BIGINT NOT NULL,
        updated_at BIGINT NOT NULL
    )
    "#,
    r#"
    CREATE TABLE IF NOT EXISTS helpdesk_agents (
        agent_id TEXT PRIMARY KEY,
        display_name TEXT NOT NULL,
        avatar_url TEXT,
        status TEXT NOT NULL,
        current_ticket_id TEXT,
        last_heartbeat_at BIGINT NOT NULL,
        created_at BIGINT NOT NULL,
        updated_at BIGINT NOT NULL
    )
    "#,
    r#"
    CREATE INDEX IF NOT EXISTS idx_helpdesk_agents_status_updated
    ON helpdesk_agents(status, updated_at)
    "#,
    r#"
    CREATE TABLE IF NOT EXISTS helpdesk_tickets (
        ticket_id TEXT PRIMARY KEY,
        client_id TEXT NOT NULL,
        client_display_name TEXT,
        device_id TEXT,
        requested_by TEXT,
        title TEXT,
        description TEXT,
        difficulty TEXT,
        estimated_minutes BIGINT,
        summary TEXT,
        status TEXT NOT NULL,
        assigned_agent_id TEXT,
        latest_agent_report TEXT,
        latest_agent_report_by TEXT,
        latest_agent_report_at BIGINT,
        opening_deadline_at BIGINT,
        created_at BIGINT NOT NULL,
        updated_at BIGINT NOT NULL
    )
    "#,
    r#"
    CREATE INDEX IF NOT EXISTS idx_helpdesk_tickets_status_created
    ON helpdesk_tickets(status, created_at)
    "#,
    r#"
    CREATE INDEX IF NOT EXISTS idx_helpdesk_tickets_agent
    ON helpdesk_tickets(assigned_agent_id, updated_at)
    "#,
    r#"
    CREATE TABLE IF NOT EXISTS helpdesk_ticket_assignments (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ticket_id TEXT NOT NULL,
        agent_id TEXT NOT NULL,
        status TEXT NOT NULL,
        created_at BIGINT NOT NULL,
        updated_at BIGINT NOT NULL
    )
    "#,
    r#"
    CREATE INDEX IF NOT EXISTS idx_helpdesk_ticket_assignments_ticket
    ON helpdesk_ticket_assignments(ticket_id, updated_at DESC)
    "#,
    r#"
    CREATE TABLE IF NOT EXISTS helpdesk_agent_heartbeats (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        agent_id TEXT NOT NULL,
        status TEXT NOT NULL,
        created_at BIGINT NOT NULL
    )
    "#,
    r#"
    CREATE INDEX IF NOT EXISTS idx_helpdesk_agent_heartbeats_agent_created
    ON helpdesk_agent_heartbeats(agent_id, created_at DESC)
    "#,
    r#"
    CREATE TABLE IF NOT EXISTS helpdesk_audit_events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        entity_type TEXT NOT NULL,
        entity_id TEXT NOT NULL,
        event_type TEXT NOT NULL,
        payload TEXT,
        created_at BIGINT NOT NULL
    )
    "#,
    r#"
    CREATE INDEX IF NOT EXISTS idx_helpdesk_audit_entity
    ON helpdesk_audit_events(entity_type, entity_id, created_at DESC)
    "#,
];

pub async fn connect_postgres(database_url: &str) -> anyhow::Result<PgPool> {
    let database_url = normalize_database_url(database_url);
    PgPoolOptions::new()
        .max_connections(5)
        .connect(&database_url)
        .await
        .context("failed to connect to Postgres")
}

pub async fn init_postgres_helpdesk_schema(pool: &PgPool) -> anyhow::Result<()> {
    for statement in POSTGRES_HELPDESK_SCHEMA {
        sqlx::query(statement)
            .execute(pool)
            .await
            .context("failed to apply Postgres helpdesk schema statement")?;
    }
    Ok(())
}

pub async fn bootstrap_helpdesk_from_sqlite(
    database_url: &str,
    sqlite_path: &Path,
) -> anyhow::Result<HelpdeskPostgresBootstrapSummary> {
    let sqlite_pool = connect_sqlite(sqlite_path).await?;
    let snapshot = fetch_helpdesk_snapshot_from_sqlite(&sqlite_pool).await?;

    let pg_pool = connect_postgres(database_url).await?;
    init_postgres_helpdesk_schema(&pg_pool).await?;
    apply_helpdesk_snapshot_to_postgres(&pg_pool, &snapshot).await?;

    Ok(HelpdeskPostgresBootstrapSummary::from_snapshot(&snapshot))
}

pub fn normalize_database_url(url: &str) -> String {
    if url.contains("sslmode=") {
        url.to_string()
    } else {
        format!("{url}?sslmode=require")
    }
}

#[derive(Debug, Clone, Default)]
struct HelpdeskSnapshot {
    authorized_agents: Vec<AuthorizedAgentRecord>,
    agents: Vec<AgentRecord>,
    tickets: Vec<TicketRecord>,
    assignments: Vec<AssignmentRecord>,
    heartbeats: Vec<HeartbeatRecord>,
    audit_events: Vec<AuditEventRecord>,
}

#[derive(Debug, Clone)]
struct AuthorizedAgentRecord {
    agent_id: String,
    display_name: Option<String>,
    created_at: i64,
    updated_at: i64,
}

#[derive(Debug, Clone)]
struct AgentRecord {
    agent_id: String,
    display_name: String,
    avatar_url: Option<String>,
    status: String,
    current_ticket_id: Option<String>,
    last_heartbeat_at: i64,
    created_at: i64,
    updated_at: i64,
}

#[derive(Debug, Clone)]
struct TicketRecord {
    ticket_id: String,
    client_id: String,
    client_display_name: Option<String>,
    device_id: Option<String>,
    requested_by: Option<String>,
    title: Option<String>,
    description: Option<String>,
    difficulty: Option<String>,
    estimated_minutes: Option<i64>,
    summary: Option<String>,
    status: String,
    assigned_agent_id: Option<String>,
    latest_agent_report: Option<String>,
    latest_agent_report_by: Option<String>,
    latest_agent_report_at: Option<i64>,
    opening_deadline_at: Option<i64>,
    created_at: i64,
    updated_at: i64,
}

#[derive(Debug, Clone)]
struct AssignmentRecord {
    id: i64,
    ticket_id: String,
    agent_id: String,
    status: String,
    created_at: i64,
    updated_at: i64,
}

#[derive(Debug, Clone)]
struct HeartbeatRecord {
    id: i64,
    agent_id: String,
    status: String,
    created_at: i64,
}

#[derive(Debug, Clone)]
struct AuditEventRecord {
    id: i64,
    entity_type: String,
    entity_id: String,
    event_type: String,
    payload: Option<String>,
    created_at: i64,
}

async fn fetch_helpdesk_snapshot_from_sqlite(pool: &SqlitePool) -> anyhow::Result<HelpdeskSnapshot> {
    Ok(HelpdeskSnapshot {
        authorized_agents: fetch_sqlite_authorized_agents(pool).await?,
        agents: fetch_sqlite_agents(pool).await?,
        tickets: fetch_sqlite_tickets(pool).await?,
        assignments: fetch_sqlite_assignments(pool).await?,
        heartbeats: fetch_sqlite_heartbeats(pool).await?,
        audit_events: fetch_sqlite_audit_events(pool).await?,
    })
}

async fn fetch_sqlite_authorized_agents(pool: &SqlitePool) -> anyhow::Result<Vec<AuthorizedAgentRecord>> {
    let rows = sqlx::query(
        r#"
        SELECT agent_id, display_name, created_at, updated_at
        FROM helpdesk_authorized_agents
        ORDER BY created_at ASC, agent_id ASC
        "#,
    )
    .fetch_all(pool)
    .await
    .context("failed to read SQLite authorized helpdesk agents")?;

    Ok(rows
        .into_iter()
        .map(|row| AuthorizedAgentRecord {
            agent_id: row.get("agent_id"),
            display_name: row.get("display_name"),
            created_at: row.get("created_at"),
            updated_at: row.get("updated_at"),
        })
        .collect())
}

async fn fetch_sqlite_agents(pool: &SqlitePool) -> anyhow::Result<Vec<AgentRecord>> {
    let rows = sqlx::query(
        r#"
        SELECT agent_id, display_name, avatar_url, status, current_ticket_id, last_heartbeat_at, created_at, updated_at
        FROM helpdesk_agents
        ORDER BY created_at ASC, agent_id ASC
        "#,
    )
    .fetch_all(pool)
    .await
    .context("failed to read SQLite helpdesk agents")?;

    Ok(rows
        .into_iter()
        .map(|row| AgentRecord {
            agent_id: row.get("agent_id"),
            display_name: row.get("display_name"),
            avatar_url: row.get("avatar_url"),
            status: row.get("status"),
            current_ticket_id: row.get("current_ticket_id"),
            last_heartbeat_at: row.get("last_heartbeat_at"),
            created_at: row.get("created_at"),
            updated_at: row.get("updated_at"),
        })
        .collect())
}

async fn fetch_sqlite_tickets(pool: &SqlitePool) -> anyhow::Result<Vec<TicketRecord>> {
    let rows = sqlx::query(
        r#"
        SELECT ticket_id, client_id, client_display_name, device_id, requested_by, title,
               description, difficulty, estimated_minutes, summary, status, assigned_agent_id,
               latest_agent_report, latest_agent_report_by, latest_agent_report_at,
               opening_deadline_at, created_at, updated_at
        FROM helpdesk_tickets
        ORDER BY created_at ASC, ticket_id ASC
        "#,
    )
    .fetch_all(pool)
    .await
    .context("failed to read SQLite helpdesk tickets")?;

    Ok(rows
        .into_iter()
        .map(|row| TicketRecord {
            ticket_id: row.get("ticket_id"),
            client_id: row.get("client_id"),
            client_display_name: row.get("client_display_name"),
            device_id: row.get("device_id"),
            requested_by: row.get("requested_by"),
            title: row.get("title"),
            description: row.get("description"),
            difficulty: row.get("difficulty"),
            estimated_minutes: row.get("estimated_minutes"),
            summary: row.get("summary"),
            status: row.get("status"),
            assigned_agent_id: row.get("assigned_agent_id"),
            latest_agent_report: row.get("latest_agent_report"),
            latest_agent_report_by: row.get("latest_agent_report_by"),
            latest_agent_report_at: row.get("latest_agent_report_at"),
            opening_deadline_at: row.get("opening_deadline_at"),
            created_at: row.get("created_at"),
            updated_at: row.get("updated_at"),
        })
        .collect())
}

async fn fetch_sqlite_assignments(pool: &SqlitePool) -> anyhow::Result<Vec<AssignmentRecord>> {
    let rows = sqlx::query(
        r#"
        SELECT id, ticket_id, agent_id, status, created_at, updated_at
        FROM helpdesk_ticket_assignments
        ORDER BY id ASC
        "#,
    )
    .fetch_all(pool)
    .await
    .context("failed to read SQLite helpdesk assignments")?;

    Ok(rows
        .into_iter()
        .map(|row| AssignmentRecord {
            id: row.get("id"),
            ticket_id: row.get("ticket_id"),
            agent_id: row.get("agent_id"),
            status: row.get("status"),
            created_at: row.get("created_at"),
            updated_at: row.get("updated_at"),
        })
        .collect())
}

async fn fetch_sqlite_heartbeats(pool: &SqlitePool) -> anyhow::Result<Vec<HeartbeatRecord>> {
    let rows = sqlx::query(
        r#"
        SELECT id, agent_id, status, created_at
        FROM helpdesk_agent_heartbeats
        ORDER BY id ASC
        "#,
    )
    .fetch_all(pool)
    .await
    .context("failed to read SQLite helpdesk heartbeats")?;

    Ok(rows
        .into_iter()
        .map(|row| HeartbeatRecord {
            id: row.get("id"),
            agent_id: row.get("agent_id"),
            status: row.get("status"),
            created_at: row.get("created_at"),
        })
        .collect())
}

async fn fetch_sqlite_audit_events(pool: &SqlitePool) -> anyhow::Result<Vec<AuditEventRecord>> {
    let rows = sqlx::query(
        r#"
        SELECT id, entity_type, entity_id, event_type, payload, created_at
        FROM helpdesk_audit_events
        ORDER BY id ASC
        "#,
    )
    .fetch_all(pool)
    .await
    .context("failed to read SQLite helpdesk audit events")?;

    Ok(rows
        .into_iter()
        .map(|row| AuditEventRecord {
            id: row.get("id"),
            entity_type: row.get("entity_type"),
            entity_id: row.get("entity_id"),
            event_type: row.get("event_type"),
            payload: row.get("payload"),
            created_at: row.get("created_at"),
        })
        .collect())
}

async fn apply_helpdesk_snapshot_to_postgres(
    pool: &PgPool,
    snapshot: &HelpdeskSnapshot,
) -> anyhow::Result<()> {
    let mut tx = pool
        .begin()
        .await
        .context("failed to open Postgres transaction for helpdesk bootstrap")?;

    for table in [
        "helpdesk_audit_events",
        "helpdesk_agent_heartbeats",
        "helpdesk_ticket_assignments",
        "helpdesk_tickets",
        "helpdesk_agents",
        "helpdesk_authorized_agents",
    ] {
        sqlx::query(&format!("TRUNCATE TABLE {table} RESTART IDENTITY CASCADE"))
            .execute(&mut *tx)
            .await
            .with_context(|| format!("failed to clear Postgres helpdesk table '{table}'"))?;
    }

    for row in &snapshot.authorized_agents {
        sqlx::query(
            r#"
            INSERT INTO helpdesk_authorized_agents (agent_id, display_name, created_at, updated_at)
            VALUES ($1, $2, $3, $4)
            "#,
        )
        .bind(&row.agent_id)
        .bind(row.display_name.as_deref())
        .bind(row.created_at)
        .bind(row.updated_at)
        .execute(&mut *tx)
        .await
        .with_context(|| format!("failed to import authorized agent '{}'", row.agent_id))?;
    }

    for row in &snapshot.agents {
        sqlx::query(
            r#"
            INSERT INTO helpdesk_agents (
                agent_id, display_name, avatar_url, status, current_ticket_id,
                last_heartbeat_at, created_at, updated_at
            )
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
            "#,
        )
        .bind(&row.agent_id)
        .bind(&row.display_name)
        .bind(row.avatar_url.as_deref())
        .bind(&row.status)
        .bind(row.current_ticket_id.as_deref())
        .bind(row.last_heartbeat_at)
        .bind(row.created_at)
        .bind(row.updated_at)
        .execute(&mut *tx)
        .await
        .with_context(|| format!("failed to import helpdesk agent '{}'", row.agent_id))?;
    }

    for row in &snapshot.tickets {
        sqlx::query(
            r#"
            INSERT INTO helpdesk_tickets (
                ticket_id, client_id, client_display_name, device_id, requested_by, title,
                description, difficulty, estimated_minutes, summary, status, assigned_agent_id,
                latest_agent_report, latest_agent_report_by, latest_agent_report_at,
                opening_deadline_at, created_at, updated_at
            )
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
            "#,
        )
        .bind(&row.ticket_id)
        .bind(&row.client_id)
        .bind(row.client_display_name.as_deref())
        .bind(row.device_id.as_deref())
        .bind(row.requested_by.as_deref())
        .bind(row.title.as_deref())
        .bind(row.description.as_deref())
        .bind(row.difficulty.as_deref())
        .bind(row.estimated_minutes)
        .bind(row.summary.as_deref())
        .bind(&row.status)
        .bind(row.assigned_agent_id.as_deref())
        .bind(row.latest_agent_report.as_deref())
        .bind(row.latest_agent_report_by.as_deref())
        .bind(row.latest_agent_report_at)
        .bind(row.opening_deadline_at)
        .bind(row.created_at)
        .bind(row.updated_at)
        .execute(&mut *tx)
        .await
        .with_context(|| format!("failed to import ticket '{}'", row.ticket_id))?;
    }

    for row in &snapshot.assignments {
        sqlx::query(
            r#"
            INSERT INTO helpdesk_ticket_assignments (id, ticket_id, agent_id, status, created_at, updated_at)
            VALUES ($1, $2, $3, $4, $5, $6)
            "#,
        )
        .bind(row.id)
        .bind(&row.ticket_id)
        .bind(&row.agent_id)
        .bind(&row.status)
        .bind(row.created_at)
        .bind(row.updated_at)
        .execute(&mut *tx)
        .await
        .with_context(|| format!("failed to import assignment '{}'", row.id))?;
    }

    for row in &snapshot.heartbeats {
        sqlx::query(
            r#"
            INSERT INTO helpdesk_agent_heartbeats (id, agent_id, status, created_at)
            VALUES ($1, $2, $3, $4)
            "#,
        )
        .bind(row.id)
        .bind(&row.agent_id)
        .bind(&row.status)
        .bind(row.created_at)
        .execute(&mut *tx)
        .await
        .with_context(|| format!("failed to import heartbeat '{}'", row.id))?;
    }

    for row in &snapshot.audit_events {
        sqlx::query(
            r#"
            INSERT INTO helpdesk_audit_events (id, entity_type, entity_id, event_type, payload, created_at)
            VALUES ($1, $2, $3, $4, $5, $6)
            "#,
        )
        .bind(row.id)
        .bind(&row.entity_type)
        .bind(&row.entity_id)
        .bind(&row.event_type)
        .bind(row.payload.as_deref())
        .bind(row.created_at)
        .execute(&mut *tx)
        .await
        .with_context(|| format!("failed to import audit event '{}'", row.id))?;
    }

    reset_identity_sequence(&mut tx, "helpdesk_ticket_assignments_id_seq", "helpdesk_ticket_assignments").await?;
    reset_identity_sequence(&mut tx, "helpdesk_agent_heartbeats_id_seq", "helpdesk_agent_heartbeats").await?;
    reset_identity_sequence(&mut tx, "helpdesk_audit_events_id_seq", "helpdesk_audit_events").await?;

    tx.commit()
        .await
        .context("failed to commit Postgres helpdesk bootstrap transaction")?;

    Ok(())
}

async fn reset_identity_sequence(
    tx: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    sequence_name: &str,
    table_name: &str,
) -> anyhow::Result<()> {
    let statement = format!(
        r#"
        SELECT CASE
            WHEN COALESCE((SELECT MAX(id) FROM {table_name}), 0) > 0
                THEN setval('{sequence_name}', (SELECT MAX(id) FROM {table_name}), true)
            ELSE setval('{sequence_name}', 1, false)
        END
        "#
    );
    sqlx::query(&statement)
        .execute(&mut **tx)
        .await
        .with_context(|| format!("failed to reset identity sequence '{sequence_name}'"))?;
    Ok(())
}
